// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ChatItem 对话条目
 */
export class ChatItem {
    /**
     * Creates a new ChatItem instance.
     * @param {Partial<ChatItem>} [$$source = {}] - The source object to create the ChatItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["workingDir"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChatItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatItem(/** @type {Partial<ChatItem>} */($$parsedSource));
    }
}

/**
 * MCPServerItem represents an MCP server entry for frontend display.
 */
export class MCPServerItem {
    /**
     * Creates a new MCPServerItem instance.
     * @param {Partial<MCPServerItem>} [$$source = {}] - The source object to create the MCPServerItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["command"] = "";
        }
        if (!("toolCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["toolCount"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["toolNames"] = undefined;
        }
        if (!("connected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["connected"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MCPServerItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MCPServerItem}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("toolNames" in $$parsedSource) {
            $$parsedSource["toolNames"] = $$createField5_0($$parsedSource["toolNames"]);
        }
        return new MCPServerItem(/** @type {Partial<MCPServerItem>} */($$parsedSource));
    }
}

/**
 * Message 单条消息
 */
export class Message {
    /**
     * Creates a new Message instance.
     * @param {Partial<Message>} [$$source = {}] - The source object to create the Message.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("role" in $$source)) {
            /**
             * user / assistant / system
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("time" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["time"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Message}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Message(/** @type {Partial<Message>} */($$parsedSource));
    }
}

/**
 * ProjectEntry 持久化存储的项目条目
 */
export class ProjectEntry {
    /**
     * Creates a new ProjectEntry instance.
     * @param {Partial<ProjectEntry>} [$$source = {}] - The source object to create the ProjectEntry.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProjectEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectEntry(/** @type {Partial<ProjectEntry>} */($$parsedSource));
    }
}

/**
 * SendOptions controls session loading behaviour for SendMessage.
 */
export class SendOptions {
    /**
     * Creates a new SendOptions instance.
     * @param {Partial<SendOptions>} [$$source = {}] - The source object to create the SendOptions.
     */
    constructor($$source = {}) {
        if (!("continueSession" in $$source)) {
            /**
             * ContinueSession loads the most recent session for the current working directory
             * before sending the message (equivalent to `deepcodex chat -c`).
             * @member
             * @type {boolean}
             */
            this["continueSession"] = false;
        }
        if (!("resumeSessionID" in $$source)) {
            /**
             * ResumeSessionID loads a specific session by ID before sending the message
             * (equivalent to `deepcodex chat -r <id>`).
             * Takes precedence over ContinueSession when non-empty.
             * @member
             * @type {string}
             */
            this["resumeSessionID"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SendOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SendOptions}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SendOptions(/** @type {Partial<SendOptions>} */($$parsedSource));
    }
}

/**
 * SkillItem represents a skill entry for frontend display.
 */
export class SkillItem {
    /**
     * Creates a new SkillItem instance.
     * @param {Partial<SkillItem>} [$$source = {}] - The source object to create the SkillItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["toolPerms"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SkillItem}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("toolPerms" in $$parsedSource) {
            $$parsedSource["toolPerms"] = $$createField3_0($$parsedSource["toolPerms"]);
        }
        return new SkillItem(/** @type {Partial<SkillItem>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
