// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AGUIAttachment is the subset of CopilotKit / AG-UI input content parts that
 * deepcodex can forward to the harness. Today only images are converted into
 * multimodal LLM blocks; other modalities are ignored by buildInputMessage.
 */
export class AGUIAttachment {
    /**
     * Creates a new AGUIAttachment instance.
     * @param {Partial<AGUIAttachment>} [$$source = {}] - The source object to create the AGUIAttachment.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["type"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {AGUIInputSource | undefined}
             */
            this["source"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["metadata"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AGUIAttachment instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AGUIAttachment}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("source" in $$parsedSource) {
            $$parsedSource["source"] = $$createField1_0($$parsedSource["source"]);
        }
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField2_0($$parsedSource["metadata"]);
        }
        return new AGUIAttachment(/** @type {Partial<AGUIAttachment>} */($$parsedSource));
    }
}

export class AGUIInputSource {
    /**
     * Creates a new AGUIInputSource instance.
     * @param {Partial<AGUIInputSource>} [$$source = {}] - The source object to create the AGUIInputSource.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["type"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["value"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["mimeType"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AGUIInputSource instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AGUIInputSource}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AGUIInputSource(/** @type {Partial<AGUIInputSource>} */($$parsedSource));
    }
}

/**
 * ChatItem 对话条目
 */
export class ChatItem {
    /**
     * Creates a new ChatItem instance.
     * @param {Partial<ChatItem>} [$$source = {}] - The source object to create the ChatItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["workingDir"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChatItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatItem(/** @type {Partial<ChatItem>} */($$parsedSource));
    }
}

/**
 * ChatItem represents a chat session in the UI, with metadata for display.
 */
export class InputMessage {
    /**
     * Creates a new InputMessage instance.
     * @param {Partial<InputMessage>} [$$source = {}] - The source object to create the InputMessage.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["chat_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["model"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["user_input"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["image_paths"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {AGUIAttachment[] | undefined}
             */
            this["attachments"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ProjectEntry | undefined}
             */
            this["proj"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {SendOptions | undefined}
             */
            this["send_options"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InputMessage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InputMessage}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $$createType4;
        const $$createField5_0 = $$createType5;
        const $$createField6_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("image_paths" in $$parsedSource) {
            $$parsedSource["image_paths"] = $$createField3_0($$parsedSource["image_paths"]);
        }
        if ("attachments" in $$parsedSource) {
            $$parsedSource["attachments"] = $$createField4_0($$parsedSource["attachments"]);
        }
        if ("proj" in $$parsedSource) {
            $$parsedSource["proj"] = $$createField5_0($$parsedSource["proj"]);
        }
        if ("send_options" in $$parsedSource) {
            $$parsedSource["send_options"] = $$createField6_0($$parsedSource["send_options"]);
        }
        return new InputMessage(/** @type {Partial<InputMessage>} */($$parsedSource));
    }
}

/**
 * MCPServerItem represents an MCP server entry for frontend display.
 */
export class MCPServerItem {
    /**
     * Creates a new MCPServerItem instance.
     * @param {Partial<MCPServerItem>} [$$source = {}] - The source object to create the MCPServerItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["command"] = "";
        }
        if (!("toolCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["toolCount"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["toolNames"] = undefined;
        }
        if (!("connected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["connected"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MCPServerItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MCPServerItem}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("toolNames" in $$parsedSource) {
            $$parsedSource["toolNames"] = $$createField5_0($$parsedSource["toolNames"]);
        }
        return new MCPServerItem(/** @type {Partial<MCPServerItem>} */($$parsedSource));
    }
}

/**
 * Message 单条消息
 */
export class Message {
    /**
     * Creates a new Message instance.
     * @param {Partial<Message>} [$$source = {}] - The source object to create the Message.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("role" in $$source)) {
            /**
             * user / assistant / system
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("time" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["time"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Message}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Message(/** @type {Partial<Message>} */($$parsedSource));
    }
}

/**
 * ProjectEntry 持久化存储的项目条目
 */
export class ProjectEntry {
    /**
     * Creates a new ProjectEntry instance.
     * @param {Partial<ProjectEntry>} [$$source = {}] - The source object to create the ProjectEntry.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProjectEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectEntry(/** @type {Partial<ProjectEntry>} */($$parsedSource));
    }
}

/**
 * SendOptions controls session loading behaviour for SendMessage.
 */
export class SendOptions {
    /**
     * Creates a new SendOptions instance.
     * @param {Partial<SendOptions>} [$$source = {}] - The source object to create the SendOptions.
     */
    constructor($$source = {}) {
        if (!("continueSession" in $$source)) {
            /**
             * ContinueSession loads the most recent session for the current working directory
             * before sending the message (equivalent to `deepcodex chat -c`).
             * @member
             * @type {boolean}
             */
            this["continueSession"] = false;
        }
        if (!("resumeSessionID" in $$source)) {
            /**
             * ResumeSessionID loads a specific session by ID before sending the message
             * (equivalent to `deepcodex chat -r <id>`).
             * Takes precedence over ContinueSession when non-empty.
             * @member
             * @type {string}
             */
            this["resumeSessionID"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SendOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SendOptions}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SendOptions(/** @type {Partial<SendOptions>} */($$parsedSource));
    }
}

/**
 * SkillItem represents a skill entry for frontend display.
 */
export class SkillItem {
    /**
     * Creates a new SkillItem instance.
     * @param {Partial<SkillItem>} [$$source = {}] - The source object to create the SkillItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["toolPerms"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SkillItem}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("toolPerms" in $$parsedSource) {
            $$parsedSource["toolPerms"] = $$createField3_0($$parsedSource["toolPerms"]);
        }
        return new SkillItem(/** @type {Partial<SkillItem>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = AGUIInputSource.createFrom;
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = AGUIAttachment.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = ProjectEntry.createFrom;
const $$createType6 = SendOptions.createFrom;
