package kiro

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// SteeringConfig holds configuration for generating a steering file.
type SteeringConfig struct {
	Inclusion        string            `json:"inclusion"`
	FileMatchPattern string            `json:"fileMatchPattern,omitempty"`
	Sections         map[string]string `json:"sections"`
}

// GenerateSteeringFile creates a Kiro-compatible steering Markdown file
// from the given config and writes it to the specified directory.
func GenerateSteeringFile(dir, name string, config SteeringConfig) (string, error) {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", fmt.Errorf("creating steering directory: %w", err)
	}

	var b strings.Builder

	// Front matter
	b.WriteString("---\n")
	b.WriteString(fmt.Sprintf("inclusion: %s\n", config.Inclusion))
	if config.FileMatchPattern != "" {
		b.WriteString(fmt.Sprintf("fileMatchPattern: '%s'\n", config.FileMatchPattern))
	}
	b.WriteString("---\n\n")

	// Sections
	for title, content := range config.Sections {
		b.WriteString(fmt.Sprintf("## %s\n\n%s\n\n", title, content))
	}

	path := filepath.Join(dir, name+".md")
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return "", fmt.Errorf("writing steering file: %w", err)
	}
	return path, nil
}

// GenerateRuntimeSteering creates a steering file from runtime state.
func GenerateRuntimeSteering(dir string, toolCount, cmdCount int, sessionID string) (string, error) {
	config := SteeringConfig{
		Inclusion: "auto",
		Sections: map[string]string{
			"Runtime Info": fmt.Sprintf(
				"- Tools: %d\n- Commands: %d\n- Session: %s",
				toolCount, cmdCount, sessionID,
			),
			"Usage": "This steering file was auto-generated by gocode Go port.",
		},
	}
	return GenerateSteeringFile(dir, "gocode-runtime", config)
}
