// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ModelInfo 描述一个模型条目, 是 ListModels 的返回元素.
 * 
 * 该结构同时被 wails 绑定层使用, 字段以 camelCase 暴露给前端.
 */
export class ModelInfo {
    /**
     * Creates a new ModelInfo instance.
     * @param {Partial<ModelInfo>} [$$source = {}] - The source object to create the ModelInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * ID 是模型的真实标识符, 如 "gpt-5.4", "claude-sonnet-4-6".
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * DisplayName 是用于 UI 展示的友好名称 (默认等于 ID).
             * @member
             * @type {string | undefined}
             */
            this["displayName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Provider 是该模型所属的 provider 名称 (即 ProviderConfig.Name).
             * @member
             * @type {string | undefined}
             */
            this["provider"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Source 表示这一条来自哪里: "config" | "remote" | "alias".
             * 用于前端区分: 是用户配置的 / 远程接口拉取的 / 内置别名.
             * @member
             * @type {string | undefined}
             */
            this["source"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModelInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelInfo(/** @type {Partial<ModelInfo>} */($$parsedSource));
    }
}

/**
 * ProviderConfig 描述一个用户配置的 LLM 提供商。
 * 
 * 一个 ProviderConfig 同时承载:
 *   - 鉴权信息 (APIKey / AuthToken)
 *   - 接入信息 (BaseURL)
 *   - 该 provider 下用户希望暴露的模型列表
 * 
 * 该结构体既被持久化为 JSON, 也被 wails 绑定暴露给前端,
 * 因此所有字段都使用 json tag, 并尽量保持与前端一致的 camelCase 风格。
 */
export class ProviderConfig {
    /**
     * Creates a new ProviderConfig instance.
     * @param {Partial<ProviderConfig>} [$$source = {}] - The source object to create the ProviderConfig.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * Name 是用户为该 provider 起的唯一别名 (e.g. "my-openai").
             * 用于在配置文件中索引, 必填且全局唯一.
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * Kind 标识底层协议类型, 取值: "anthropic" | "openai" | "openai-compat" | "gemini" | "xai".
             * 决定使用哪个 Provider 实现.
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * BaseURL 是该 provider 的 API 接入地址 (可选, 留空使用对应 Kind 的默认值).
             * @member
             * @type {string | undefined}
             */
            this["baseUrl"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * APIKey 是该 provider 的鉴权 key (明文存储, 仅本机使用).
             * @member
             * @type {string | undefined}
             */
            this["apiKey"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * AuthToken 仅 anthropic 使用, 对应 ANTHROPIC_AUTH_TOKEN.
             * @member
             * @type {string | undefined}
             */
            this["authToken"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Models 是该 provider 下用户已知/启用的模型 ID 列表.
             * 例如 ["gpt-5.4", "gpt-4o", "o3-mini"].
             * @member
             * @type {string[] | undefined}
             */
            this["models"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * DefaultModel 是该 provider 下推荐使用的默认模型.
             * @member
             * @type {string | undefined}
             */
            this["defaultModel"] = undefined;
        }
        if (!("enabled" in $$source)) {
            /**
             * Enabled 标识该 provider 是否启用; 为 false 时 ResolveProvider 不会自动选用它.
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * CreatedAt / UpdatedAt 用于前端展示, 由保存逻辑自动维护.
             * @member
             * @type {number | undefined}
             */
            this["createdAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["updatedAt"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProviderConfig}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField5_0($$parsedSource["models"]);
        }
        return new ProviderConfig(/** @type {Partial<ProviderConfig>} */($$parsedSource));
    }
}

/**
 * ProviderTemplate 描述一个内置 LLM 提供商模板.
 * 
 * 模板代表「我们知道如何接入这个 provider, 这是它的官方默认值」, 但用户尚未
 * 必须填写 API Key 才能真正启用. 启动时会将所有模板写入 providers.json,
 * 用户可在前端模型设置界面补齐 API Key.
 */
export class ProviderTemplate {
    /**
     * Creates a new ProviderTemplate instance.
     * @param {Partial<ProviderTemplate>} [$$source = {}] - The source object to create the ProviderTemplate.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * Name 是该模板生成的 provider 默认名称, 同时作为 providers.json 中的 key.
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * Kind 标识底层协议类型, 取值与 ProviderConfig.Kind 一致.
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * DisplayName 是用于 UI 展示的友好名称.
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("baseUrl" in $$source)) {
            /**
             * BaseURL 是该 provider 的默认 API 接入地址.
             * @member
             * @type {string}
             */
            this["baseUrl"] = "";
        }
        if (!("models" in $$source)) {
            /**
             * Models 是该 provider 推荐暴露的模型 ID 列表.
             * @member
             * @type {string[]}
             */
            this["models"] = [];
        }
        if (!("defaultModel" in $$source)) {
            /**
             * DefaultModel 是该 provider 推荐使用的默认模型.
             * @member
             * @type {string}
             */
            this["defaultModel"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * AuthEnv 是该 provider 用于读取 API Key 的环境变量名 (可选).
             * 启动时若发现环境变量已设置, 会自动填入 ProviderConfig.APIKey.
             * @member
             * @type {string | undefined}
             */
            this["authEnv"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderTemplate instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProviderTemplate}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField4_0($$parsedSource["models"]);
        }
        return new ProviderTemplate(/** @type {Partial<ProviderTemplate>} */($$parsedSource));
    }
}

/**
 * ProvidersConfig 是 ~/.deepcodex/providers.json 的根结构.
 */
export class ProvidersConfig {
    /**
     * Creates a new ProvidersConfig instance.
     * @param {Partial<ProvidersConfig>} [$$source = {}] - The source object to create the ProvidersConfig.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * Version 用于后续兼容升级.
             * @member
             * @type {number}
             */
            this["version"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * ActiveProvider 是当前默认启用的 provider 名称.
             * @member
             * @type {string | undefined}
             */
            this["activeProvider"] = undefined;
        }
        if (!("providers" in $$source)) {
            /**
             * Providers 是已配置的 provider 列表.
             * @member
             * @type {ProviderConfig[]}
             */
            this["providers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProvidersConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProvidersConfig}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("providers" in $$parsedSource) {
            $$parsedSource["providers"] = $$createField2_0($$parsedSource["providers"]);
        }
        return new ProvidersConfig(/** @type {Partial<ProvidersConfig>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ProviderConfig.createFrom;
const $$createType2 = $Create.Array($$createType1);
