// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as apiclient$0 from "./agent/apiclient/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "./app/models.js";

/**
 * AddProject 添加一个本地目录作为项目
 * name 可为空，若空则使用目录名
 * @param {string} dirPath
 * @param {string} name
 * @returns {$CancellablePromise<app$0.ProjectEntry>}
 */
export function AddProject(dirPath, name) {
    return $Call.ByID(1121292353, dirPath, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Close 关闭（前端调用）
 * @returns {$CancellablePromise<void>}
 */
export function Close() {
    return $Call.ByID(906152507);
}

/**
 * CreateChat 新建对话
 * @param {string} projectID
 * @param {string} title
 * @returns {$CancellablePromise<app$0.ChatItem>}
 */
export function CreateChat(projectID, title) {
    return $Call.ByID(2849591563, projectID, title).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * DeleteProject 删除一个项目（不删除目录本身）
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteProject(id) {
    return $Call.ByID(3379369923, id);
}

/**
 * DeleteProvider 删除指定名称的 LLM 提供商配置.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteProvider(name) {
    return $Call.ByID(3297626303, name);
}

/**
 * EnsureDefaultProviders 把所有内置 provider 模板写入到 providers.json.
 * 
 * 已存在的 provider 不会被覆盖, 仅在某些字段为空时补齐默认值.
 * 应用启动时会自动调用一次, 也可由前端在用户点击「重置默认」时主动调用.
 * @returns {$CancellablePromise<apiclient$0.ProvidersConfig | null>}
 */
export function EnsureDefaultProviders() {
    return $Call.ByID(3226040850).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetProject 根据 ID 获取项目信息
 * @param {string} id
 * @returns {$CancellablePromise<app$0.ProjectEntry>}
 */
export function GetProject(id) {
    return $Call.ByID(4040571020, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetProvidersConfig 返回完整的 providers.json 文件内容 (含 ActiveProvider).
 * 
 * 注意: 该方法返回的 ProviderConfig 中 APIKey/AuthToken 被脱敏, 仅供展示.
 * @returns {$CancellablePromise<apiclient$0.ProvidersConfig | null>}
 */
export function GetProvidersConfig() {
    return $Call.ByID(3236013941).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetProvidersConfigPath 返回配置文件的绝对路径, 便于前端展示/打开.
 * @returns {$CancellablePromise<string>}
 */
export function GetProvidersConfigPath() {
    return $Call.ByID(2388578502);
}

/**
 * GetSessionMessages 获取一个会话的历史消息
 * @param {string} projectID
 * @param {string} sessionID
 * @returns {$CancellablePromise<app$0.Message[]>}
 */
export function GetSessionMessages(projectID, sessionID) {
    return $Call.ByID(988970873, projectID, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * SelectDirectory 打开原生目录选择对话框，返回用户选择的目录路径
 * 此方法需要在 App 层调用 runtime.OpenDirectoryDialog，这里仅作占位
 * 实际对话框调用在 app.go 中的 App 结构体方法里
 * @param {string} projectPath
 * @returns {$CancellablePromise<string>}
 */
export function GetSessionsDir(projectPath) {
    return $Call.ByID(3011375797, projectPath);
}

/**
 * GetUsage 获取用量
 * @param {string} projectID
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetUsage(projectID) {
    return $Call.ByID(2234764926, projectID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * ListChats 获取指定项目的会话列表
 * @param {string} projectID
 * @returns {$CancellablePromise<app$0.ChatItem[]>}
 */
export function ListChats(projectID) {
    return $Call.ByID(386131212, projectID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * ListProjects 列出所有已添加的项目
 * @returns {$CancellablePromise<app$0.ProjectEntry[]>}
 */
export function ListProjects() {
    return $Call.ByID(2721360259).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * ListProviderModels 返回某个 provider 下的可用模型列表.
 * 
 * providerName 为空时使用 ActiveProvider.
 * 解析顺序: 配置中的 Models -> 远程 /models 接口 -> 内置别名兜底.
 * @param {string} providerName
 * @returns {$CancellablePromise<apiclient$0.ModelInfo[]>}
 */
export function ListProviderModels(providerName) {
    return $Call.ByID(3026634666, providerName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * ListProviders 返回所有已配置的 LLM 提供商 (api key 已脱敏).
 * @returns {$CancellablePromise<apiclient$0.ProviderConfig[]>}
 */
export function ListProviders() {
    return $Call.ByID(4005662969).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * ListSessionsForProject 直接从磁盘读取项目的会话列表（无需 Harness 初始化）
 * @param {string} projectID
 * @returns {$CancellablePromise<app$0.ChatItem[]>}
 */
export function ListSessionsForProject(projectID) {
    return $Call.ByID(551062180, projectID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * ListSupportedProviders 返回所有内置支持的 LLM 提供商模板.
 * 
 * 该接口与 ListProviders 互补:
 *   - ListProviders        → 用户实际配置 (含已脱敏 API Key)
 *   - ListSupportedProviders → 系统知道如何接入的全部 provider 元数据
 * 
 * 前端可以用它在模型下拉中展示「即使尚未配置 key 也能看到」的全集.
 * @returns {$CancellablePromise<apiclient$0.ProviderTemplate[]>}
 */
export function ListSupportedProviders() {
    return $Call.ByID(3600971573).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * OpenBrowserWindow 使用 Wails v3 官方多窗口 API 打开内置浏览器窗口。
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function OpenBrowserWindow(url) {
    return $Call.ByID(331446675, url);
}

/**
 * RenameProject 重命名项目
 * @param {string} id
 * @param {string} newName
 * @returns {$CancellablePromise<void>}
 */
export function RenameProject(id, newName) {
    return $Call.ByID(3728890856, id, newName);
}

/**
 * SaveProvider 新增或更新一个 LLM 提供商配置.
 * 
 * 当传入的 APIKey 为脱敏占位 (以 "****" 开头) 时, 保留文件中已有的 key,
 * 这样前端可以安全地把 ListProviders 的结果直接回传, 不需要重新输入 key.
 * @param {apiclient$0.ProviderConfig} p
 * @returns {$CancellablePromise<void>}
 */
export function SaveProvider(p) {
    return $Call.ByID(1885182733, p);
}

/**
 * SelectDirectory 打开原生目录选择对话框，返回用户选择的路径
 * @returns {$CancellablePromise<string>}
 */
export function SelectDirectory() {
    return $Call.ByID(1735672136);
}

/**
 * SelectImageFiles 打开原生文件选择对话框，允许用户挑选一张或多张图片。
 * 返回所选图片的绝对路径列表；用户取消时返回空数组。
 * 前端在输入框输入 `@` 时会触发此对话框，把所选路径以 `@<path>` 形式回填到输入文本中。
 * @returns {$CancellablePromise<string[]>}
 */
export function SelectImageFiles() {
    return $Call.ByID(398204413).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * SendMessage 发送消息（流式）
 * imagePaths 为可选的图片路径列表（前端通过 SelectImageFiles 选择得到），非空时走多模态通道。
 * @param {string} projectID
 * @param {string} chatID
 * @param {string} content
 * @param {string[]} imagePaths
 * @param {app$0.SendOptions} opts
 * @returns {$CancellablePromise<app$0.Message>}
 */
export function SendMessage(projectID, chatID, content, imagePaths, opts) {
    return $Call.ByID(1496882310, projectID, chatID, content, imagePaths, opts).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * SetActiveProvider 设置当前默认使用的 provider.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function SetActiveProvider(name) {
    return $Call.ByID(3216417132, name);
}

/**
 * StopMessage 中止当前对话
 * @param {string} projectID
 * @returns {$CancellablePromise<void>}
 */
export function StopMessage(projectID) {
    return $Call.ByID(1485307612, projectID);
}

// Private type creation functions
const $$createType0 = app$0.ProjectEntry.createFrom;
const $$createType1 = app$0.ChatItem.createFrom;
const $$createType2 = apiclient$0.ProvidersConfig.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = app$0.Message.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Map($Create.Any, $Create.Any);
const $$createType7 = $Create.Array($$createType1);
const $$createType8 = $Create.Array($$createType0);
const $$createType9 = apiclient$0.ModelInfo.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = apiclient$0.ProviderConfig.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = apiclient$0.ProviderTemplate.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = $Create.Array($Create.Any);
