// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {apiclient} from '../models';

export function CreateChat(arg1:string):Promise<main.ChatItem>;

export function DeleteProvider(arg1:string):Promise<void>;

export function GetProvidersConfig():Promise<apiclient.ProvidersConfig>;

export function GetProvidersConfigPath():Promise<string>;

export function GetUsage():Promise<Record<string, any>>;

export function ListChats():Promise<Array<main.ChatItem>>;

export function ListProjects():Promise<Array<main.Project>>;

export function ListProviderModels(arg1:string):Promise<Array<apiclient.ModelInfo>>;

export function ListProviders():Promise<Array<apiclient.ProviderConfig>>;

export function SaveProvider(arg1:apiclient.ProviderConfig):Promise<void>;

export function SendMessage(arg1:string,arg2:string):Promise<main.Message>;

export function SendMessageSync(arg1:string,arg2:string):Promise<main.Message>;

export function SetActiveProvider(arg1:string):Promise<void>;
