// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProject(arg1, arg2) {
  return window['go']['main']['App']['AddProject'](arg1, arg2);
}

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function CreateChat(arg1, arg2) {
  return window['go']['main']['App']['CreateChat'](arg1, arg2);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteProvider(arg1) {
  return window['go']['main']['App']['DeleteProvider'](arg1);
}

export function EnsureDefaultProviders() {
  return window['go']['main']['App']['EnsureDefaultProviders']();
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetProvidersConfig() {
  return window['go']['main']['App']['GetProvidersConfig']();
}

export function GetProvidersConfigPath() {
  return window['go']['main']['App']['GetProvidersConfigPath']();
}

export function GetSessionMessages(arg1, arg2) {
  return window['go']['main']['App']['GetSessionMessages'](arg1, arg2);
}

export function GetSessionsDir(arg1) {
  return window['go']['main']['App']['GetSessionsDir'](arg1);
}

export function GetUsage(arg1) {
  return window['go']['main']['App']['GetUsage'](arg1);
}

export function ListChats(arg1) {
  return window['go']['main']['App']['ListChats'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListProviderModels(arg1) {
  return window['go']['main']['App']['ListProviderModels'](arg1);
}

export function ListProviders() {
  return window['go']['main']['App']['ListProviders']();
}

export function ListSessionsForProject(arg1) {
  return window['go']['main']['App']['ListSessionsForProject'](arg1);
}

export function ListSupportedProviders() {
  return window['go']['main']['App']['ListSupportedProviders']();
}

export function RenameProject(arg1, arg2) {
  return window['go']['main']['App']['RenameProject'](arg1, arg2);
}

export function SaveProvider(arg1) {
  return window['go']['main']['App']['SaveProvider'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SendMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3, arg4);
}

export function SetActiveProvider(arg1) {
  return window['go']['main']['App']['SetActiveProvider'](arg1);
}

export function StopMessage(arg1) {
  return window['go']['main']['App']['StopMessage'](arg1);
}
