// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateChat(arg1) {
  return window['go']['main']['App']['CreateChat'](arg1);
}

export function GetUsage() {
  return window['go']['main']['App']['GetUsage']();
}

export function ListChats() {
  return window['go']['main']['App']['ListChats']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function SendMessageSync(arg1, arg2) {
  return window['go']['main']['App']['SendMessageSync'](arg1, arg2);
}
